// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAdk1DM-vQKkJZMwiPd2rb2RHkSoYDkvY',
    appId: '1:743309110659:web:baf9dcfb8a1fc51664dab6',
    messagingSenderId: '743309110659',
    projectId: 'lntproject-1c62f',
    authDomain: 'lntproject-1c62f.firebaseapp.com',
    storageBucket: 'lntproject-1c62f.firebasestorage.app',
    measurementId: 'G-WQW91BYJYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR78UiIredemMhq5bFO5sqvnuavQRU8WU',
    appId: '1:743309110659:android:a460f0bd7d46639964dab6',
    messagingSenderId: '743309110659',
    projectId: 'lntproject-1c62f',
    storageBucket: 'lntproject-1c62f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMMUeYKw3jyqHJyRZNV5ZRLDGHOrg2raU',
    appId: '1:743309110659:ios:3cb0c215a50ad17964dab6',
    messagingSenderId: '743309110659',
    projectId: 'lntproject-1c62f',
    storageBucket: 'lntproject-1c62f.firebasestorage.app',
    iosBundleId: 'com.example.mathLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMMUeYKw3jyqHJyRZNV5ZRLDGHOrg2raU',
    appId: '1:743309110659:ios:3cb0c215a50ad17964dab6',
    messagingSenderId: '743309110659',
    projectId: 'lntproject-1c62f',
    storageBucket: 'lntproject-1c62f.firebasestorage.app',
    iosBundleId: 'com.example.mathLearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAdk1DM-vQKkJZMwiPd2rb2RHkSoYDkvY',
    appId: '1:743309110659:web:1c3729ed2774c6b364dab6',
    messagingSenderId: '743309110659',
    projectId: 'lntproject-1c62f',
    authDomain: 'lntproject-1c62f.firebaseapp.com',
    storageBucket: 'lntproject-1c62f.firebasestorage.app',
    measurementId: 'G-EEEFZE2JLS',
  );
}
